# Site settings
# These are used to personalize your new site.
title: Timmy A Jenkins # your name here
logo: "/images/Handshake profile picture.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Technology in Computer-Science (class of 2026)
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/profiles/zwys3t">View My Resume</a>
  <br /><br />
  <a href="www.linkedin.com/in/timmy-jenkins1827">View My LinkedIn Profile</a>
repository: "Metalmilitia26/Metalmilitia26.github.io"
github_username:  Metalmilitia26 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

